### ISSUE TITLE
Not Block

### ISSUE THREAD

**Issue by TeaqariaWTF** [Dr-TSNG/TwiFucker#6] opened 2022-02-28 19:25 UTC
latest version does not block sponsors

**Comment by Dr-TSNG** [comment] 2022-03-04 09:19
Cannot reproduce

**Comment by Dr-TSNG** [comment] 2022-03-18 11:46
Check 1.2

**Comment by Dr-TSNG** [comment] 2022-03-18 11:46
Duplicate of #7

**Closed by Dr-TSNG** 2022-03-18 11:46 UTC
